[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "venom"
authors = [{name = "Debby", email = "ogheneakpotor@vemon"}]
dynamic = ["version", "description"]
